import { Offer, OfferUI } from '@/types';

export const mapOfferDbToUi = (offer: Offer): OfferUI => ({
  id: offer.id,
  titleAr: offer.title_ar,
  description: offer.description,
  type: offer.type,
  discountPercentage: offer.discount_percentage,
  discountAmount: offer.discount_amount,
  minQuantity: offer.min_quantity,
  freeQuantity: offer.free_quantity,
  minAmount: offer.min_amount,
  applicableProducts: offer.applicable_products,
  applicableCategories: offer.applicable_categories,
  bannerImage: offer.banner_image,
  startDate: offer.start_date ? new Date(offer.start_date) : null,
  endDate: offer.end_date ? new Date(offer.end_date) : null,
  isActive: offer.is_active,
  priority: offer.priority,
  autoApply: offer.auto_apply,
  createdAt: new Date(offer.created_at),
  updatedAt: new Date(offer.updated_at),
});

export const mapOfferUiToDb = (offer: OfferUI): Offer => ({
  id: offer.id,
  title_ar: offer.titleAr,
  description: offer.description,
  type: offer.type,
  discount_percentage: offer.discountPercentage,
  discount_amount: offer.discountAmount,
  min_quantity: offer.minQuantity,
  free_quantity: offer.freeQuantity,
  min_amount: offer.minAmount,
  applicable_products: offer.applicableProducts,
  applicable_categories: offer.applicableCategories,
  banner_image: offer.bannerImage,
  start_date: offer.startDate ? offer.startDate.toISOString() : null,
  end_date: offer.endDate ? offer.endDate.toISOString() : null,
  is_active: offer.isActive,
  priority: offer.priority,
  auto_apply: offer.autoApply,
  created_at: offer.createdAt.toISOString(),
  updated_at: offer.updatedAt.toISOString(),
});
